# Generated by Django 5.1.3 on 2024-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Bakery', 'Bakery'), ('Meat', 'Meat'), ('Beverages', 'Beverages'), ('Snacks', 'Snacks'), ('Frozen Foods', 'Frozen Foods'), ('Household Items', 'Household Items')], default='N/A', max_length=50),
        ),
    ]
