# Generated by Django 5.1.3 on 2024-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_useractionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="is_shared",
            field=models.BooleanField(default=True),
        ),
    ]
