# Generated by Django 5.1.4 on 2024-12-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cartitem_is_shared'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='price',
        ),
    ]
