# Generated by Django 5.1.4 on 2024-12-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
