--
-- PostgreSQL database dump
--

-- Dumped from database version 14.15 (Debian 14.15-1.pgdg120+1)
-- Dumped by pg_dump version 14.15 (Debian 14.15-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO "user";

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO "user";

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO "user";

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO "user";

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO "user";

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO "user";

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO "user";

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO "user";

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO "user";

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO "user";

--
-- Name: main_cartitem; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.main_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    added_at timestamp with time zone NOT NULL,
    is_purchased boolean NOT NULL,
    added_by_id integer,
    item_id bigint NOT NULL,
    cart_id bigint NOT NULL,
    is_shared boolean NOT NULL,
    CONSTRAINT main_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.main_cartitem OWNER TO "user";

--
-- Name: main_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.main_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_groceryitem; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.main_groceryitem (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    price numeric(6,2),
    availability boolean NOT NULL,
    category character varying(50) NOT NULL
);


ALTER TABLE public.main_groceryitem OWNER TO "user";

--
-- Name: main_groceryitem_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.main_groceryitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_groceryitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_notification; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.main_notification (
    id bigint NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.main_notification OWNER TO "user";

--
-- Name: main_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.main_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_paymentinfo; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.main_paymentinfo (
    id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.main_paymentinfo OWNER TO "user";

--
-- Name: main_paymentinfo_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.main_paymentinfo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_paymentinfo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_purchasehistory; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.main_purchasehistory (
    id bigint NOT NULL,
    purchased_at timestamp with time zone NOT NULL,
    cart_item_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.main_purchasehistory OWNER TO "user";

--
-- Name: main_purchasehistory_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.main_purchasehistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_purchasehistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_sharedcart; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.main_sharedcart (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.main_sharedcart OWNER TO "user";

--
-- Name: main_sharedcart_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.main_sharedcart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_sharedcart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_sharedcart_users; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.main_sharedcart_users (
    id bigint NOT NULL,
    sharedcart_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.main_sharedcart_users OWNER TO "user";

--
-- Name: main_sharedcart_users_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.main_sharedcart_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_sharedcart_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_useractionhistory; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public.main_useractionhistory (
    id bigint NOT NULL,
    action_type character varying(10) NOT NULL,
    quantity integer,
    "timestamp" timestamp with time zone NOT NULL,
    details text NOT NULL,
    cart_id bigint,
    item_id bigint,
    user_id integer NOT NULL,
    CONSTRAINT main_useractionhistory_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.main_useractionhistory OWNER TO "user";

--
-- Name: main_useractionhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public.main_useractionhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_useractionhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add grocery item	7	add_groceryitem
26	Can change grocery item	7	change_groceryitem
27	Can delete grocery item	7	delete_groceryitem
28	Can view grocery item	7	view_groceryitem
29	Can add cart item	8	add_cartitem
30	Can change cart item	8	change_cartitem
31	Can delete cart item	8	delete_cartitem
32	Can view cart item	8	view_cartitem
33	Can add notification	9	add_notification
34	Can change notification	9	change_notification
35	Can delete notification	9	delete_notification
36	Can view notification	9	view_notification
37	Can add payment info	10	add_paymentinfo
38	Can change payment info	10	change_paymentinfo
39	Can delete payment info	10	delete_paymentinfo
40	Can view payment info	10	view_paymentinfo
41	Can add purchase history	11	add_purchasehistory
42	Can change purchase history	11	change_purchasehistory
43	Can delete purchase history	11	delete_purchasehistory
44	Can view purchase history	11	view_purchasehistory
45	Can add shared cart	12	add_sharedcart
46	Can change shared cart	12	change_sharedcart
47	Can delete shared cart	12	delete_sharedcart
48	Can view shared cart	12	view_sharedcart
49	Can add user action history	13	add_useractionhistory
50	Can change user action history	13	change_useractionhistory
51	Can delete user action history	13	delete_useractionhistory
52	Can view user action history	13	view_useractionhistory
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
2	pbkdf2_sha256$870000$Xen877VtbDlyI5wVl1wA9G$f1fqhD4ddmROUnCatuBiZmDS7HNg9/jgharJDuO46vw=	2024-12-09 13:29:25.644093+00	t	sattam			sattam@yopmail.com	t	t	2024-12-09 13:16:19.520181+00
3	pbkdf2_sha256$870000$AVn8CT5eBJGA5Zd4xzdWPa$7AckaSaSPbnFcHRIz1NNCddpW4MtTSDPA7p6GvnrJak=	2024-12-09 13:34:08.16394+00	t	Yasser			Yasser@yopmail.com	t	t	2024-12-09 13:16:50.29528+00
1	pbkdf2_sha256$870000$nlWaiEmB2U78PDiMM1drlB$YiKh7njMAdZkWFcEFVAJSUnvrWVrOKpNo3rfyiqJqpA=	2024-12-09 13:34:14.053343+00	t	mbfsj			mbfsj1@hotmail.com	t	t	2024-12-09 02:36:07.052536+00
4	pbkdf2_sha256$870000$Hm46vHJnD4F5tuWIXxWRw4$UFY1A9YUYcaQ3CuvrshMc2VX3IaWghB/kUmkkZ625eI=	2024-12-09 13:34:45.351321+00	t	Mohammed			mohammed@yopmail.com	t	t	2024-12-09 13:17:26.822967+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2024-12-09 13:32:05.178126+00	1	The Bank	2	[{"changed": {"fields": ["Users"]}}]	12	1
2	2024-12-09 13:34:06.211081+00	1	Apples	1	[{"added": {}}]	7	1
3	2024-12-09 13:34:59.999822+00	4	Bank	2	[{"changed": {"fields": ["Users"]}}]	12	1
4	2024-12-09 13:35:28.924422+00	1	The Bank	2	[{"changed": {"fields": ["Users"]}}]	12	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	main	groceryitem
8	main	cartitem
9	main	notification
10	main	paymentinfo
11	main	purchasehistory
12	main	sharedcart
13	main	useractionhistory
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2024-12-09 02:33:29.924859+00
2	auth	0001_initial	2024-12-09 02:33:29.942566+00
3	admin	0001_initial	2024-12-09 02:33:29.948377+00
4	admin	0002_logentry_remove_auto_add	2024-12-09 02:33:29.950424+00
5	admin	0003_logentry_add_action_flag_choices	2024-12-09 02:33:29.952351+00
6	contenttypes	0002_remove_content_type_name	2024-12-09 02:33:29.956063+00
7	auth	0002_alter_permission_name_max_length	2024-12-09 02:33:29.958303+00
8	auth	0003_alter_user_email_max_length	2024-12-09 02:33:29.960275+00
9	auth	0004_alter_user_username_opts	2024-12-09 02:33:29.962083+00
10	auth	0005_alter_user_last_login_null	2024-12-09 02:33:29.964317+00
11	auth	0006_require_contenttypes_0002	2024-12-09 02:33:29.964767+00
12	auth	0007_alter_validators_add_error_messages	2024-12-09 02:33:29.968057+00
13	auth	0008_alter_user_username_max_length	2024-12-09 02:33:29.971451+00
14	auth	0009_alter_user_last_name_max_length	2024-12-09 02:33:29.974264+00
15	auth	0010_alter_group_name_max_length	2024-12-09 02:33:29.976758+00
16	auth	0011_update_proxy_permissions	2024-12-09 02:33:29.978629+00
17	auth	0012_alter_user_first_name_max_length	2024-12-09 02:33:29.981344+00
18	main	0001_initial	2024-12-09 02:33:30.011333+00
19	main	0002_groceryitem_category	2024-12-09 02:33:30.012717+00
20	main	0003_useractionhistory	2024-12-09 02:33:30.019726+00
21	main	0004_cartitem_is_shared	2024-12-09 02:33:30.023634+00
22	sessions	0001_initial	2024-12-09 02:33:30.027205+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
x19vdq5vx5i47hg2fxnghi69x4tvzdow	.eJxVjL0OwiAURt-F2RAEe0sd3X0Gcn9AqgaS0k7Gd1eSDrp8w3dOzksF3NYcthaXMIs6q6M6_H6E_IilA7ljuVXNtazLTLoreqdNX6vE52V3_wIZW-7ZU8QECYkAefBAZLw48WaMk7GUrAFvLFoHfsTETNPA6Ags8XcdqfcHBCY4qg:1tKTea:l4TJ-dP5pGSO2vUYMjdKBijVbb2-i1eJZbqjRGDprUQ	2024-12-23 02:37:44.601896+00
4utr9askwn7dju3m79tyvmzj4m2m33ss	.eJxVjL0OwiAURt-F2RAEe0sd3X0Gcn9AqgaS0k7Gd1eSDrp8w3dOzksF3NYcthaXMIs6q6M6_H6E_IilA7ljuVXNtazLTLoreqdNX6vE52V3_wIZW-7ZU8QECYkAefBAZLw48WaMk7GUrAFvLFoHfsTETNPA6Ags8XcdqfcHBCY4qg:1tKTfE:WRU2c8i4jxN_TQ-mcnS3QCKZKERvi2un8lr3iKOxFGY	2024-12-23 02:38:24.199594+00
junbjxh9cqevpl8stmvb7gjqnye2ny85	.eJxVjL0OwiAURt-F2RAEe0sd3X0Gcn9AqgaS0k7Gd1eSDrp8w3dOzksF3NYcthaXMIs6q6M6_H6E_IilA7ljuVXNtazLTLoreqdNX6vE52V3_wIZW-7ZU8QECYkAefBAZLw48WaMk7GUrAFvLFoHfsTETNPA6Ags8XcdqfcHBCY4qg:1tKUAx:QexREqMyQNSKJEGL9MawDlNxlprwR4JL0wC5i6QV4Tw	2024-12-23 03:11:11.284093+00
4i9xuu7kpxg4lex0df4a5ejkn6gh93bu	.eJxVjL0OwiAURt-F2RAEe0sd3X0Gcn9AqgaS0k7Gd1eSDrp8w3dOzksF3NYcthaXMIs6q6M6_H6E_IilA7ljuVXNtazLTLoreqdNX6vE52V3_wIZW-7ZU8QECYkAefBAZLw48WaMk7GUrAFvLFoHfsTETNPA6Ags8XcdqfcHBCY4qg:1tKUCP:6-r5uwSPoeyCBMQqmUG2zE6KpRQ-BPmMc1kdKN0xZpw	2024-12-23 03:12:41.96239+00
t88ujv1dr2qfpm8ewezhhyajhyr165b1	.eJxVjMsOwiAUBf-FtSFQCA-X7v0Gci8HpGrapLQr479rky50e2bmvESibW1p62VJI8RZDOL0uzHlR5l2gDtNt1nmeVqXkeWuyIN2eZ1RnpfD_Tto1Nu3Js2VPUdrHLSxCL5GBTXUbFUwShsPqsWygUd0HBwCYgQFp1FqyeL9Ae5NOKQ:1tKdez:vC_bGNn6OpQ0aWli6Vxg7ccPFJZjhIX8_04JTz9LXK8	2024-12-23 13:18:49.648353+00
m8p608httrey0hg7tix2vahbzz1nka31	.eJxVjMsOwiAUBf-FtSFQCA-X7v0Gci8HpGrapLQr479rky50e2bmvESibW1p62VJI8RZDOL0uzHlR5l2gDtNt1nmeVqXkeWuyIN2eZ1RnpfD_Tto1Nu3Js2VPUdrHLSxCL5GBTXUbFUwShsPqsWygUd0HBwCYgQFp1FqyeL9Ae5NOKQ:1tKdpF:rG2lNRxTp-vZonE969q1C8e6ATfxUu2Q8Ey3Larqp8k	2024-12-23 13:29:25.644742+00
ix7b6xthp2xtmro0s8hibbpicwa0ukrm	.eJxVjMsOwiAQRf-FtSEUyoy4dN9vIDM8pGogKe3K-O_apAvd3nPOfQlP21r81tPi5yguwojT78YUHqnuIN6p3poMra7LzHJX5EG7nFpMz-vh_h0U6uVbI1oVUGUzKITgNIEFw0GjNnlkBiDMDMM52REdWSCrFTFlZXRw5Fi8P8CnN2s:1tKdto:GxTN331_4O7LghQi2WyB4XrO2lCu8fz5I4C6FtkEcyg	2024-12-23 13:34:08.164666+00
95hk6kjtz5inf9ajtj3ut2y6jbhh62i6	.eJxVjL0OwiAURt-F2RAEe0sd3X0Gcn9AqgaS0k7Gd1eSDrp8w3dOzksF3NYcthaXMIs6q6M6_H6E_IilA7ljuVXNtazLTLoreqdNX6vE52V3_wIZW-7ZU8QECYkAefBAZLw48WaMk7GUrAFvLFoHfsTETNPA6Ags8XcdqfcHBCY4qg:1tKdtu:nxMyztxpzr-x1DE3lXripusRYKK5HGz-H1E97w148RI	2024-12-23 13:34:14.055013+00
unea9tbsz4x0d9wtm9yrdnz0f01tb4w2	.eJxVjDsOwjAQBe_iGlle_zampOcM1trr4ABypDipEHeHSCmgfTPzXiLStta49bLEicVZWHH63RLlR2k74Du12yzz3NZlSnJX5EG7vM5cnpfD_Tuo1Ou3dogWgdFrz6SQdTHDGLI2wY4hJADnVRjYky-AxiUEQwBKs07kWaF4fwC3qza4:1tKduP:C8p7Nqfxdfh-l2h9RYqhQ11MFkqerQsGcqzS1EP_3Ag	2024-12-23 13:34:45.353423+00
\.


--
-- Data for Name: main_cartitem; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.main_cartitem (id, quantity, added_at, is_purchased, added_by_id, item_id, cart_id, is_shared) FROM stdin;
2	1	2024-12-09 13:34:18.972165+00	f	3	1	4	t
5	1	2024-12-09 13:35:51.341294+00	f	1	1	1	f
7	4	2024-12-09 13:35:51.998367+00	f	3	1	1	f
\.


--
-- Data for Name: main_groceryitem; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.main_groceryitem (id, name, description, price, availability, category) FROM stdin;
1	Apples	6 piece pack of apples	4.00	t	Fruits
\.


--
-- Data for Name: main_notification; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.main_notification (id, message, is_read, created_at, user_id) FROM stdin;
1	mbfsj removed Apples from The Bank	f	2024-12-09 13:35:05.412915+00	2
2	mbfsj removed Apples from The Bank	f	2024-12-09 13:35:07.474754+00	2
3	Yasser removed Apples from The Bank	f	2024-12-09 13:35:44.121521+00	2
4	Yasser removed Apples from The Bank	f	2024-12-09 13:35:44.122093+00	1
5	Yasser removed Apples from The Bank	f	2024-12-09 13:35:44.122387+00	4
6	Yasser removed Apples from The Bank	f	2024-12-09 13:35:58.280643+00	2
7	Yasser removed Apples from The Bank	f	2024-12-09 13:35:58.282038+00	1
8	Yasser removed Apples from The Bank	f	2024-12-09 13:35:58.283115+00	4
9	mbfsj updated Apples quantity to 4 in The Bank	f	2024-12-09 13:39:18.834884+00	2
10	mbfsj updated Apples quantity to 4 in The Bank	f	2024-12-09 13:39:18.835484+00	3
11	mbfsj updated Apples quantity to 4 in The Bank	f	2024-12-09 13:39:18.836231+00	4
\.


--
-- Data for Name: main_paymentinfo; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.main_paymentinfo (id, user_id) FROM stdin;
\.


--
-- Data for Name: main_purchasehistory; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.main_purchasehistory (id, purchased_at, cart_item_id, user_id) FROM stdin;
\.


--
-- Data for Name: main_sharedcart; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.main_sharedcart (id, name) FROM stdin;
2	Hello
3	Chamberlin
4	Bank
1	The Bank
\.


--
-- Data for Name: main_sharedcart_users; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.main_sharedcart_users (id, sharedcart_id, user_id) FROM stdin;
1	1	1
2	2	2
3	3	4
4	1	2
5	4	3
6	4	1
7	4	2
8	4	4
9	1	3
10	1	4
\.


--
-- Data for Name: main_useractionhistory; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public.main_useractionhistory (id, action_type, quantity, "timestamp", details, cart_id, item_id, user_id) FROM stdin;
1	ADD	1	2024-12-09 13:34:18.697324+00	Added 1 of Apples to cart The Bank.	1	1	1
2	ADD	1	2024-12-09 13:34:18.973791+00	Added 1 of Apples to cart Bank.	4	1	3
3	ADD	1	2024-12-09 13:34:20.226216+00	Added 1 of Apples to cart The Bank.	1	1	1
4	ADD	1	2024-12-09 13:34:40.862901+00	Added 1 of Apples to cart The Bank.	1	1	1
5	REMOVE	1	2024-12-09 13:35:05.410566+00	Removed 1 of Apples from cart The Bank.	1	1	1
6	REMOVE	1	2024-12-09 13:35:07.472676+00	Removed 1 of Apples from cart The Bank.	1	1	1
7	REMOVE	1	2024-12-09 13:35:44.118789+00	Removed 1 of Apples from cart The Bank.	1	1	3
8	ADD	1	2024-12-09 13:35:51.343318+00	Added 1 of Apples to cart The Bank.	1	1	1
9	ADD	1	2024-12-09 13:35:51.450917+00	Added 1 of Apples to cart The Bank.	1	1	4
10	ADD	1	2024-12-09 13:35:52.000468+00	Added 1 of Apples to cart The Bank.	1	1	3
11	REMOVE	1	2024-12-09 13:35:58.277807+00	Removed 1 of Apples from cart The Bank.	1	1	3
12	MODIFY	4	2024-12-09 13:39:18.832691+00	Modified Apples quantity to 4 in cart The Bank.	1	1	1
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 4, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 4, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 22, true);


--
-- Name: main_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.main_cartitem_id_seq', 7, true);


--
-- Name: main_groceryitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.main_groceryitem_id_seq', 1, true);


--
-- Name: main_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.main_notification_id_seq', 11, true);


--
-- Name: main_paymentinfo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.main_paymentinfo_id_seq', 1, false);


--
-- Name: main_purchasehistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.main_purchasehistory_id_seq', 1, false);


--
-- Name: main_sharedcart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.main_sharedcart_id_seq', 4, true);


--
-- Name: main_sharedcart_users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.main_sharedcart_users_id_seq', 10, true);


--
-- Name: main_useractionhistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public.main_useractionhistory_id_seq', 12, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: main_cartitem main_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_cartitem
    ADD CONSTRAINT main_cartitem_pkey PRIMARY KEY (id);


--
-- Name: main_groceryitem main_groceryitem_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_groceryitem
    ADD CONSTRAINT main_groceryitem_pkey PRIMARY KEY (id);


--
-- Name: main_notification main_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_notification
    ADD CONSTRAINT main_notification_pkey PRIMARY KEY (id);


--
-- Name: main_paymentinfo main_paymentinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_paymentinfo
    ADD CONSTRAINT main_paymentinfo_pkey PRIMARY KEY (id);


--
-- Name: main_paymentinfo main_paymentinfo_user_id_key; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_paymentinfo
    ADD CONSTRAINT main_paymentinfo_user_id_key UNIQUE (user_id);


--
-- Name: main_purchasehistory main_purchasehistory_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_purchasehistory
    ADD CONSTRAINT main_purchasehistory_pkey PRIMARY KEY (id);


--
-- Name: main_sharedcart main_sharedcart_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_sharedcart
    ADD CONSTRAINT main_sharedcart_pkey PRIMARY KEY (id);


--
-- Name: main_sharedcart_users main_sharedcart_users_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_sharedcart_users
    ADD CONSTRAINT main_sharedcart_users_pkey PRIMARY KEY (id);


--
-- Name: main_sharedcart_users main_sharedcart_users_sharedcart_id_user_id_4d1fdce0_uniq; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_sharedcart_users
    ADD CONSTRAINT main_sharedcart_users_sharedcart_id_user_id_4d1fdce0_uniq UNIQUE (sharedcart_id, user_id);


--
-- Name: main_useractionhistory main_useractionhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_useractionhistory
    ADD CONSTRAINT main_useractionhistory_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: main_cartitem_added_by_id_db2564bf; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_cartitem_added_by_id_db2564bf ON public.main_cartitem USING btree (added_by_id);


--
-- Name: main_cartitem_cart_id_8357cf81; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_cartitem_cart_id_8357cf81 ON public.main_cartitem USING btree (cart_id);


--
-- Name: main_cartitem_item_id_bf0a5c4b; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_cartitem_item_id_bf0a5c4b ON public.main_cartitem USING btree (item_id);


--
-- Name: main_notification_user_id_8efbf76d; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_notification_user_id_8efbf76d ON public.main_notification USING btree (user_id);


--
-- Name: main_purchasehistory_cart_item_id_716176b3; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_purchasehistory_cart_item_id_716176b3 ON public.main_purchasehistory USING btree (cart_item_id);


--
-- Name: main_purchasehistory_user_id_7abbf287; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_purchasehistory_user_id_7abbf287 ON public.main_purchasehistory USING btree (user_id);


--
-- Name: main_sharedcart_users_sharedcart_id_f13d5440; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_sharedcart_users_sharedcart_id_f13d5440 ON public.main_sharedcart_users USING btree (sharedcart_id);


--
-- Name: main_sharedcart_users_user_id_18d74a0c; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_sharedcart_users_user_id_18d74a0c ON public.main_sharedcart_users USING btree (user_id);


--
-- Name: main_useractionhistory_cart_id_2337b574; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_useractionhistory_cart_id_2337b574 ON public.main_useractionhistory USING btree (cart_id);


--
-- Name: main_useractionhistory_item_id_80ac1f4a; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_useractionhistory_item_id_80ac1f4a ON public.main_useractionhistory USING btree (item_id);


--
-- Name: main_useractionhistory_user_id_08274d32; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX main_useractionhistory_user_id_08274d32 ON public.main_useractionhistory USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_cartitem main_cartitem_added_by_id_db2564bf_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_cartitem
    ADD CONSTRAINT main_cartitem_added_by_id_db2564bf_fk_auth_user_id FOREIGN KEY (added_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_cartitem main_cartitem_cart_id_8357cf81_fk_main_sharedcart_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_cartitem
    ADD CONSTRAINT main_cartitem_cart_id_8357cf81_fk_main_sharedcart_id FOREIGN KEY (cart_id) REFERENCES public.main_sharedcart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_cartitem main_cartitem_item_id_bf0a5c4b_fk_main_groceryitem_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_cartitem
    ADD CONSTRAINT main_cartitem_item_id_bf0a5c4b_fk_main_groceryitem_id FOREIGN KEY (item_id) REFERENCES public.main_groceryitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_notification main_notification_user_id_8efbf76d_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_notification
    ADD CONSTRAINT main_notification_user_id_8efbf76d_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_paymentinfo main_paymentinfo_user_id_39615579_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_paymentinfo
    ADD CONSTRAINT main_paymentinfo_user_id_39615579_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_purchasehistory main_purchasehistory_cart_item_id_716176b3_fk_main_cartitem_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_purchasehistory
    ADD CONSTRAINT main_purchasehistory_cart_item_id_716176b3_fk_main_cartitem_id FOREIGN KEY (cart_item_id) REFERENCES public.main_cartitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_purchasehistory main_purchasehistory_user_id_7abbf287_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_purchasehistory
    ADD CONSTRAINT main_purchasehistory_user_id_7abbf287_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_sharedcart_users main_sharedcart_user_sharedcart_id_f13d5440_fk_main_shar; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_sharedcart_users
    ADD CONSTRAINT main_sharedcart_user_sharedcart_id_f13d5440_fk_main_shar FOREIGN KEY (sharedcart_id) REFERENCES public.main_sharedcart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_sharedcart_users main_sharedcart_users_user_id_18d74a0c_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_sharedcart_users
    ADD CONSTRAINT main_sharedcart_users_user_id_18d74a0c_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_useractionhistory main_useractionhistory_cart_id_2337b574_fk_main_sharedcart_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_useractionhistory
    ADD CONSTRAINT main_useractionhistory_cart_id_2337b574_fk_main_sharedcart_id FOREIGN KEY (cart_id) REFERENCES public.main_sharedcart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_useractionhistory main_useractionhistory_item_id_80ac1f4a_fk_main_groceryitem_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_useractionhistory
    ADD CONSTRAINT main_useractionhistory_item_id_80ac1f4a_fk_main_groceryitem_id FOREIGN KEY (item_id) REFERENCES public.main_groceryitem(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_useractionhistory main_useractionhistory_user_id_08274d32_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public.main_useractionhistory
    ADD CONSTRAINT main_useractionhistory_user_id_08274d32_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

